%     Orientation error
e_or = transpose(cross(round(double(subs(R0_E(:,1),[q1 q2],[q(1) q(2)])),3),...
    round(double(subs(R0_E(:,1),[q1 q2],[q1_ref q2_ref])),3))) + ...
    transpose(cross(round(double(subs(R0_E(:,2),[q1 q2],[q(1) q(2)])),3),...
    round(double(subs(R0_E(:,2),[q1 q2],[q1_ref q2_ref])),3))) + ...
    transpose(cross(round(double(subs(R0_E(:,3),[q1 q2],[q(1) q(2)])),3),...
    round(double(subs(R0_E(:,3),[q1 q2],[q1_ref q2_ref])),3)));

xy_dot_buffer = round(double(subs(J_v,[q1 q2],[q(1) q(2)])),3)*[qdot(1);qdot(2)];
x_dot_real = xy_dot_buffer(1);
y_dot_real = xy_dot_buffer(2);
z_dot_real = 0;
    [q1_ref, q2_ref] = two_arm_IK(x_ref(floor(i/dt*dt_PID)+1),y_ref(floor(i/dt*dt_PID)+1),false);
